fetch_exercises:
  description: >
    The user says: **{user_request}**.

    • Parse the request to extract:
      target muscles
      equipment constraints
      body region (upper, lower, full)

    • Build a plain-language search string that will match rows in the
      *exercise_full_view* (e.g. "chest triceps barbell upper").

    • Call **pg_search_tool** with that string.  
      If zero rows are returned, relax the query once (e.g. drop an
      equipment constraint) and retry.

  expected_output: >
    A JSON array where each exercise object includes:
      id, name, movement_pattern, movement_type, body_region,
      load_class, muscles, equipments

  agent: prompt_interpreter


