fetch_exercises:
  description: >
    The user says: **{user_request}**.

    Your task is to generate a WHERE filter for an SQL query based on the user request \
    if the request does not speak about a training program your output mut be empty string.

    Your output must be an SQL query like the one delimited by triple backtics. \
    If a column has no values drop it

    WHERE
        body_region IN () AND 
        (
        load_class LIKE '%load_class%' OR
        load_class LIKE '%load_class%'
        OR equipments in ()
        )
        AND
        (
        muscles LIKE '%muscle_name%' OR
        muscles LIKE '%muscle_name%' OR 
        )
        ... 


    Possible values:

    body_region: 'upper body', 'lower body' 
    muscles: 'chest', 'shoulders', 'tricpes', 'lats', 'biceps', 'quads', 'harmstrings', 'glutes', 'calves'
    load_class: 'bodyweight', 'free-weight', 'machine'
    equipments: 'gymnastics rings, parallel bars, parallettes, pull-up bar, barbell, dumbells, kettlebell, ground'

    End possible values.

    Please note:
    If the load_class is 'Park' or 'Home' you must set load_class LIKE '%bodyweight%'
    If the load_class is 'Gym' you must select: load_class LIKE '%bodyweight%' OR load_class LIKE '%free-weight%' OR load_class LIKE '%machine%'
    If there is not a specific equipment specified in the request do not include "OR equipments in ()" in the WHERE filter

  expected_output: >
    A string containing a SQL WHERE filter for the exercise table.
    The filter should be in the format of a SQL WHERE clause, with the following structure:

    WHERE
        body_region IN () AND 
        (
        load_class LIKE '%load_class%' OR
        load_class LIKE '%load_class%'
        OR equipments in ()
        )
        AND
        (
        muscles LIKE '%muscle_name%' OR
        muscles LIKE '%muscle_name%' OR 
        )
        ... 

  agent: prompt_interpreter


