fetch_exercises:
  description: >
    Given the user request: **{user_request}**, output **ONLY** the SQL WHERE clause.
    (including the word `WHERE`, no trailing semicolon, 
    no back-ticks, no comments, no other text). 

    Your output must be an SQL query like the one delimited by triple backtics. \
    If a column has no values drop it

    Please note:
    If there is not a specific equipments specified in the prompt you MUST not filter on equipments
    
    Example in case of no equipments:
    WHERE
        body_region IN () AND 
        (
        muscles LIKE '%muscle_name%' OR
        muscles LIKE '%muscle_name%' ...
        )
    
    Example in case of equipments available:
    WHERE
        body_region IN () AND 
        (
        equipments LIKE '%equipment_name%' OR 
        equipments LIKE '%equipment_name%' ...
        )
        AND
        (
        muscles LIKE '%muscle_name%' OR
        muscles LIKE '%muscle_name%' ...
        )

    Possible values:

    body_region: 'upper body', 'lower body' 
    muscles: 'chest', 'shoulders', 'tricpes', 'lats', 'biceps', 'quads', 'harmstrings', 'glutes', 'calves'
    equipments: 'gymnastics rings, parallel bars, parallettes, pull-up bar, barbell, dumbells, kettlebell, ground'

    End possible values.

    Please note:
    If there is not a specific equipments specified in the prompt you MUST not filter on equipments
    If there are not muscles specified in the prompt you MUST not filter on muscles

  expected_output: >
    A single-line WHERE clause as plain text.

  agent: sql_query_generator


select_exercises:
  description: >
    Given the user request: **{user_needs}** and the selected exercises from the following exercises:

    {{tasks.run_query.pydantic.exercises}}


    Select some exercises following these instructions:
    
    - Select **ONLY** the exercises from the exercises provided, do not hallucinate any new exercises, do not change any name! \n
    - The number of the exercises coherent must be coherent with the duration of the traning program. 
      If the exercises are already few, select all of them. \n
    - The order of exercises should adhere to the following rule if possible: first compound and then isolation. \n
    - Do not select only compound and only isolation if not specified in the user needs. \n
    - For upper body exercises, if possible, include all the possible combinations of "movement_pattern": \n
      alternating between push and pull (or pull and push) exercises.
      including horizontal and vertical. \n
    - For total body exercises, put the legs exercises at the beginning of the training program. \n
    - If the user is Beginner prefer exercises with "load_class": machine or bodyweight. \n
    - If the user is Intermediate select more medium-advanced exercises using the "load_class" and your knowledge on the difficulty of the exercises. \n
    - If the user is Advanced select more advanced exercises using the "load_class" and your knowledge on the difficulty of the exercises. \n

  expected_output: >
    Output **ONLY** the list of dictionaries with the selected exercises.

  agent: esercises_selector