fetch_exercises:
  description: >
    The user says: **{user_request}**.

    Your task is to generate a WHERE filter for an SQL query based on the user request \
    if the request does not speak about a training program your output mut be empty string.

    Your output must be an SQL query like the one delimited by triple backtics. \
    If a column has no values drop it

    WHERE
        body_region IN () AND
        muscles LIKE '%muscle_name%' OR
        muscles LIKE '%muscle_name%' OR 
        ... 


    Possible values:

    body_region: 'upper body', 'lower body' 

    muscles: 'chest', 'shoulders', 'tricpes', 'lats', 'biceps', 'quads', 'harmstrings', 'glutes', 'calves'

  expected_output: >
    A string containing a SQL WHERE filter for the exercise table.
    The filter should be in the format of a SQL WHERE clause, with the following structure:

    WHERE
        body_region IN () AND
        muscles LIKE '%muscle_name%' OR
        muscles LIKE '%muscle_name%' OR 
        ... 

  agent: prompt_interpreter


