"""feat: nuova colonna modified columns

Revision ID: 64024b99c006
Revises: b7e57b5b06b6
Create Date: 2025-04-18 15:06:47.895219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64024b99c006'
down_revision: Union[str, None] = 'b7e57b5b06b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('exercise_type', sa.String(), nullable=False))
    op.add_column('exercises', sa.Column('body_region', sa.String(), nullable=False))
    op.add_column('exercises', sa.Column('movement_pattern', sa.String(), nullable=False))
    op.drop_column('exercises', 'description')
    op.drop_column('exercises', 'difficulty')
    op.drop_column('exercises', 'calories_burned')
    op.drop_column('exercises', 'equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('equipment', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('calories_burned', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('exercises', 'movement_pattern')
    op.drop_column('exercises', 'body_region')
    op.drop_column('exercises', 'exercise_type')
    # ### end Alembic commands ###
