"""Add experience level

Revision ID: 1de4d0a8e01b
Revises: 743de2e2b68c
Create Date: 2026-05-17 16:54:33.076368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de4d0a8e01b'
down_revision: Union[str, Sequence[str], None] = '743de2e2b68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('experience_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'experience_level')
    # ### end Alembic commands ###
