"""Add target_zone for biomechanics

Revision ID: db457a4c6d2e
Revises: 9a45dc40aba1
Create Date: 2025-12-23 11:14:54.179698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db457a4c6d2e'
down_revision: Union[str, Sequence[str], None] = '9a45dc40aba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('target_zone', sa.String(), nullable=False))
    op.add_column('exercises', sa.Column('force_type', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('secondary_muscles', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('exercises', sa.Column('mechanics', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('category', sa.String(), nullable=False))
    op.add_column('exercises', sa.Column('video_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'exercises', ['name'])
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('goals', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'goals')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'height')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'gender')
    op.drop_constraint(None, 'exercises', type_='unique')
    op.drop_column('exercises', 'video_url')
    op.drop_column('exercises', 'category')
    op.drop_column('exercises', 'mechanics')
    op.drop_column('exercises', 'secondary_muscles')
    op.drop_column('exercises', 'force_type')
    op.drop_column('exercises', 'target_zone')
    # ### end Alembic commands ###
